language: cpp
language: cpp
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
# build glog
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz -O /tmp/glog-0.3.3.tar.gz && tar -C /tmp -xzvf /tmp/glog-0.3.3.tar.gz && rm /tmp/glog-0.3.3.tar.gz
  - cd /tmp/glog-0.3.3 && ./configure && make && sudo make install && cd -
# add libunwind
  - sudo apt-get install -y libunwind7-dev
# add google perf tools
  - sudo apt-get install -y libgoogle-perftools-dev
# add semi-modern gcc
  - sudo apt-get install -qq gcc-4.8 g++-4.8
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
compiler:
  - gcc
  - clang
script: source environment_vars.sh && scons
